apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-example-deployment
  labels:
    app:
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kubernetes-example
  template:
    metadata:
      labels:
        app: kubernetes-example
    spec:
      containers:
        - name: kubernetes-example
          image: kubernetes.jar:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8090
          env:
            - name: JAVA_OPTS
              value: "-Dspring.profiles.active=test"
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "1024Mi"
              cpu: "500m"
      imagePullSecrets:
        - name: regcred